### PR TITLE
Refactor `heartbeat.py`

### PR DESCRIPTION
**Pull request by delirious-lettuce**
* Delete `src` directory
    > ["Your library does not belong in an ambiguous src or python subdirectory."](http://docs.python-guide.org/en/latest/writing/structure/#the-actual-module)
* Add tests ([run by TravisCI, 100% coverage](https://travis-ci.org/delirious-lettuce/dbcrss/jobs/262887710#L472))
    * Tests run using Python 2 use the third-party module `mock` ([which is pre-installed on Travis](https://docs.travis-ci.com/user/languages/python/#Pre-installed-packages)) but could be added to a [`requirements.txt` file if necessary](http://docs.python-guide.org/en/latest/writing/structure/#requirements-file)
    * Tests run using Python 3 use [`unittest.mock`](https://docs.python.org/3/library/unittest.mock.html#module-unittest.mock)
* Refactor `heartbeat.py`
    * Split up the code into small functions to make the code easy to read and test
    * Use `collections.deque` with the `maxlen` argument to ensure the log files will never exceed `MAX_ROWS`
    * Use `csv.DictReader` and `csv.DictWriter` to simplify IO
    * Now compatible with both Python 2 & 3

### CODE REVIEW

**Comment by ll911** [comment]
@banders can you review this?

**Comment by delirious-lettuce** [comment]
I actually wrote another version of this PR using `requests` but I wasn't sure how you guys felt about adding third-party dependencies for the main script so I sent this one first.

**Comment by ll911** [comment]
@delirious-lettuce 👍  you are welcome to send them , we will review them and merge it.

**Comment by delirious-lettuce** [comment]
@ll911 ,

Ok, sounds good. I was just kind of experimenting with the code for fun.

I came across the BCGov GitHub account by accident and have found some interesting tools/projects that have been open-sourced. I didn't realize our government was interested in open-source!

Anyways, thanks for your time!

**Comment by ll911** [comment]
@delirious-lettuce glad you find it, there are more services provided by the province in the open way, e.g https://catalogue.data.gov.bc.ca/dataset?type=WebService&download_audience=Public and https://www.bcdevexchange.org/projects.

**Pull request merged**
